INSERT INTO governorates (name, code) VALUES
  ('Tunis', 'tunis'),
  ('Ariana', 'ariana'),
  ('Ben Arous', 'ben-arous'),
  ('Manouba', 'manouba'),
  ('Nabeul', 'nabeul'),
  ('Zaghouan', 'zaghouan'),
  ('Bizerte', 'bizerte'),
  ('Béja', 'beja'),
  ('Jendouba', 'jendouba'),
  ('Le Kef', 'le-kef'),
  ('Siliana', 'siliana'),
  ('Sousse', 'sousse'),
  ('Monastir', 'monastir'),
  ('Mahdia', 'mahdia'),
  ('Sfax', 'sfax'),
  ('Kairouan', 'kairouan'),
  ('Kasserine', 'kasserine'),
  ('Sidi Bouzid', 'sidi-bouzid'),
  ('Gabès', 'gabes'),
  ('Medenine', 'medenine'),
  ('Tataouine', 'tataouine'),
  ('Gafsa', 'gafsa'),
  ('Tozeur', 'tozeur'),
  ('Kebili', 'kebili')
ON DUPLICATE KEY UPDATE name = VALUES(name), code = VALUES(code);
